version: '3.9'
services:
  app:
    build:
      context: .
      args:
      - REACT_APP_MAIN_URL= ${REACT_APP_MAIN_URL}
    # command: npm start
    ports:
      - "80:80"
    image: react
    container_name: react_container

# REACT_MAIN_URL=hello