version: '3.9'
services:
  app:
    build: 
      context: .
    ports:
      - 23000:3000
    image: sre-embarkation-manifest-frontend:1.0.0
    container_name: sre-embarkation-manifest-frontend
    