version: '3.3'
services:
  app:
    build:
      context: .
    ports:
      - 23000:80
    image: sre-embarkation-manifest-frontend:1.6.0
    container_name: sre-embarkation-manifest-frontend
    restart: unless-stopped
